---


- name: create grub-bootfiles
  ansible.builtin.template:
    src: grub.cfg.j2
    dest: "{{ tftppath }}/grub.cfg-01-{{ hostvars[item].macaddress|replace(':','-')|lower }}"
  with_items:
    - "{{ groups['clusternodes'] }}"
  delegate_to: "{{ tftphost }}"

- name: create grub-bootfiles for baremetalnodes
  ansible.builtin.template:
    src: grub.cfg.j2
    dest: "{{ tftppath }}/grub.cfg-01-{{ hostvars[item].macaddress|replace(':','-')|lower }}"
  with_items:
    - "{{ groups['baremetalclusternodes'] }}"
  delegate_to: "{{ tftphost }}"
